# Generated by Django 5.1.7 on 2025-03-29 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_apiwhitelist_dept_loginlog_menu_menubutton_menufield_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('modifier', models.CharField(blank=True, max_length=255, null=True, verbose_name='修改人')),
                ('title', models.CharField(help_text='title', max_length=100, verbose_name='标题')),
                ('content', models.TextField(help_text='content', verbose_name='content')),
                ('target_type', models.IntegerField(default=0, help_text='target type', verbose_name='target type')),
                ('creator', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('target_role', models.ManyToManyField(blank=True, to='system.role')),
            ],
            options={
                'verbose_name': 'message center',
                'db_table': 'dvadmin_message_center',
                'ordering': ('-create_datetime',),
            },
        ),
        migrations.CreateModel(
            name='MessageCenterTargetUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('modifier', models.CharField(blank=True, max_length=255, null=True, verbose_name='修改人')),
                ('is_read', models.BooleanField(blank=True, default=False, help_text='is read', null=True, verbose_name='是否')),
                ('creator', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('messagecenter', models.ForeignKey(db_constraint=False, help_text='relation message', on_delete=django.db.models.deletion.CASCADE, to='system.messagecenter', verbose_name='relation message')),
                ('users', models.ForeignKey(db_constraint=False, help_text='relation user', on_delete=django.db.models.deletion.CASCADE, related_name='target_user', to=settings.AUTH_USER_MODEL, verbose_name='relationuser')),
            ],
            options={
                'verbose_name': 'messagecenter target user sheet',
                'verbose_name_plural': 'messagecenter target user sheet',
                'db_table': 'dvadmin_message_center_target_user',
            },
        ),
        migrations.AddField(
            model_name='messagecenter',
            name='target_user',
            field=models.ManyToManyField(blank=True, related_name='user', through='system.MessageCenterTargetUser', to=settings.AUTH_USER_MODEL, verbose_name='target user'),
        ),
        migrations.CreateModel(
            name='RoleMenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('modifier', models.CharField(blank=True, max_length=255, null=True, verbose_name='修改人')),
                ('creator', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('menu', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='menu_permission', to='system.menu', verbose_name='关联菜单')),
                ('role', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='role_menu', to='system.role', verbose_name='关联角色')),
            ],
            options={
                'verbose_name': '核心模型',
                'verbose_name_plural': '核心模型',
                'abstract': False,
            },
        ),
    ]
