# Generated by Django 5.1.7 on 2025-04-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_messagecenter_messagecentertargetuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(blank=True, default='', help_text='name', max_length=40, verbose_name='name'),
        ),
    ]
