# Generated by Django 5.1.7 on 2025-04-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_users_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecenter',
            name='target_dept',
            field=models.ManyToManyField(blank=True, db_constraint=False, help_text='目标部门', to='system.dept', verbose_name='目标部门'),
        ),
    ]
